# Generated by Django 5.2.6 on 2025-12-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='يحدد ما إذا كان للمستخدم صلاحية المالك للوصول إلى لوحة المالك.', verbose_name='مالك؟'),
        ),
    ]
