# Generated by Django 5.2.6 on 2025-12-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوسيط')),
                ('icon', models.ImageField(upload_to='payment_providers/', verbose_name='أيقونة الوسيط')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('provider_type', models.CharField(choices=[('bank', 'بنك'), ('wallet', 'محفظة إلكترونية')], default='bank', max_length=10, verbose_name='نوع الوسيط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'وسيط الدفع',
                'verbose_name_plural': 'وسطاء الدفع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('booking_type', models.CharField(choices=[('hourly', 'بالساعة'), ('half_day', 'نصف يوم'), ('full_day', 'يوم كامل'), ('overnight', 'مبيت')], default='full_day', max_length=20, verbose_name='نوع الحجز')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل (رباعي)')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم هاتف العميل')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('payment_method', models.CharField(choices=[('wallet_transfer', 'تحويل محفظة'), ('bank_transfer', 'تحويل بنكي'), ('cash', 'نقداً')], default='bank_transfer', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('deposit_paid', 'تم دفع العربون'), ('paid', 'مدفوع بالكامل'), ('cash_on_arrival', 'دفع عند الوصول')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ العربون')),
                ('status', models.CharField(choices=[('pending', 'في انتظار التأكيد'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.property', verbose_name='العقار المحجوز')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('wallet_transfer', 'تحويل محفظة'), ('bank_transfer', 'تحويل بنكي'), ('cash', 'نقداً')], max_length=20, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم عملية التحويل')),
                ('payer_full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المحول (رباعي)')),
                ('payer_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف المحول')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تم التحقق؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='الحجز')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.paymentprovider', verbose_name='وسيط الدفع')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'start_datetime'], name='booking_boo_propert_f0db6a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'end_datetime'], name='booking_boo_propert_27e35e_idx'),
        ),
    ]
