# Generated by Django 5.2.6 on 2025-12-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(verbose_name='الرقم التسلسلي')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الضيف')),
                ('code', models.CharField(max_length=20, verbose_name='رمز الدعوة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='booking.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'ضيف الحجز',
                'verbose_name_plural': 'ضيوف الحجز',
                'ordering': ['serial'],
                'indexes': [models.Index(fields=['booking', 'code'], name='booking_boo_booking_ed311c_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'serial'), name='unique_guest_serial_per_booking'), models.UniqueConstraint(fields=('booking', 'code'), name='unique_guest_code_per_booking')],
            },
        ),
    ]
