# Generated by Django 5.2.6 on 2025-12-19 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingguest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_providers', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='payment_providers/', verbose_name='أيقونة الوسيط'),
        ),
    ]
