"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-urrr(=4&rsw=3s!%6qn$+fu5m%w^)elz_os^mq6d*8_g2ynkl#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'monasbah.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'unfold',  # Unfold admin theme - must be before django.contrib.admin
    'django.contrib.humanize',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',  
    'portfolio',
    'booking',
    'core',
    'accounts',
    'tailwind',
    'theme',
    'django_browser_reload',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'api',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}
CORS_ALLOW_ALL_ORIGINS = True  
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'theme' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Aden'

# Internationalization
USE_I18N = True
USE_L10N = True

# Languages
LANGUAGES = [
    ('ar', 'العربية'),
    ('en', 'English'),
]

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]



USE_TZ = True

# Authentication settings
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'portfolio:home'
LOGOUT_REDIRECT_URL = 'portfolio:home'

# Email settings for password reset (for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Tailwind CSS Configuration
#NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
#NODE_BIN_PATH = r"C:\Program Files\nodejs\node.exe"
#TAILWIND_APP_NAME = 'theme'



# Tailwind CSS Configuration (Ubuntu)
NPM_BIN_PATH = "/usr/bin/npm"    
NODE_BIN_PATH = "/usr/bin/node"    
TAILWIND_APP_NAME = 'theme'

# Internal IPs for django-browser-reload
INTERNAL_IPS = [
    '127.0.0.1',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEPOSIT_PERCENT = 20

# Unfold Admin Theme Configuration
UNFOLD = {
    "SITE_TITLE": "منصة حجز العقارات",
    "SITE_HEADER": "إدارة منصة حجز العقارات",
    "SITE_URL": "/",
    'DEFAULT_THEME': "light",
    'DEFAULT_THEME_DARK': 'dim',
    'THEME_LIST': [
        {'name': 'Light', 'value': 'light'},
        {'name': 'Dim', 'value': 'dim'},
        # Add custom themes...
    ],
    "SITE_SYMBOL": "🏛️",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "config.settings.environment_callback",
    "DASHBOARD_CALLBACK": "config.settings.dashboard_callback",
    "LOGIN": {
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },

    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "ar": "🇸🇦",               
            },
        },
    },
    
   
}

# Unfold callback functions
def environment_callback(request):
    """Return environment info for admin header"""
    return "تطوير" if DEBUG else "إنتاج"

def dashboard_callback(request, context):
    """Return dashboard data"""
    from booking.models import Booking, Payment
    from portfolio.models import Property
    
    # Add dashboard metrics to the existing context
    context.update({
        "dashboard_stats": [
            {
                "title": "إحصائيات سريعة",
                "metric": {
                    "title": "إجمالي الحجوزات",
                    "value": Booking.objects.count(),
                    "unit": "حجز",
                },
            },
            {
                "title": "الحجوزات المؤكدة",
                "metric": {
                    "title": "حجوزات مؤكدة",
                    "value": Booking.objects.filter(status='confirmed').count(),
                    "unit": "حجز",
                },
            },
            {
                "title": "العقارات الموثّقة",
                "metric": {
                    "title": "عقارات موثّقة",
                    "value": Property.objects.filter(is_verified_by_platform=True).count(),
                    "unit": "عقار",
                },
            },
            {
                "title": "المدفوعات المعلقة",
                "metric": {
                    "title": "مدفوعات معلقة",
                    "value": Payment.objects.filter(status='pending').count(),
                    "unit": "دفعة",
                },
            },
        ]
    })
    
    return context

# Django Crispy Forms Configuration
CRISPY_TEMPLATE_PACK = 'unfold'
