# Generated by Django 5.2.6 on 2025-12-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'المزايا',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField()),
                ('main_image', models.ImageField(upload_to='properties/', verbose_name='الصورة الرئيسية')),
                ('property_type', models.CharField(choices=[('chalet', 'Chalet'), ('garden', 'Garden'), ('istiraha', 'Istiraha')], default='chalet', max_length=20)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_half_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_price_negotiable', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='خط العرض للموقع على الخريطة', max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='خط الطول للموقع على الخريطة', max_digits=9, null=True, verbose_name='خط الطول')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('privacy_rating', models.PositiveSmallIntegerField(default=3)),
                ('is_verified_by_platform', models.BooleanField(default=False)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='portfolio.amenity')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'صورة معرض',
                'verbose_name_plural': 'صور المعرض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='portfolio.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقييم عقار',
                'verbose_name_plural': 'تقييمات العقارات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('property', 'user'), name='unique_property_review_per_user')],
            },
        ),
    ]
