# Generated by Django 5.2.6 on 2025-12-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='يتم إنشاؤه تلقائياً من الاسم', max_length=200, unique=True, verbose_name='رابط العقار (Slug)'),
        ),
    ]
